Able to create a new user and query the ledger
* With our newly generated admin eCert, we will now communicate
  with the CA server once more to register and enroll a new user.
  This user will be the identity we use when querying and updating
  the ledger. Its important to note that it is the admin identity
  that is issuing the registration and enrollment calls for our
  new user.

  Send the register and enroll calls for user1:
    node registerUser.js

    I immediately ran into the following issue:
      Store path:/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/hfc-key-store
      Successfully loaded admin from persistence
      Failed to register: Error: Calling register endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]

    This is obviously the same issue I was running into before.
    Hardcoding the ip to 192.168.99.100, and re-running produced
    the following:
      Store path:/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/hfc-key-store
      Successfully loaded admin from persistence
      Successfully registered user1 - secret:BetLiODcNcQm
      Successfully enrolled member user "user1"
      User1 was successfully registered and enrolled and is ready to intreact with the fabric network

    And the following in the ca.example.com logs:
      2018/02/07 15:48:08 [DEBUG] Received request
      POST /api/v1/register
      Authorization: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI4VENDQVplZ0F3SUJBZ0lVRHVKSGFtTHVrbTE5cHltQmtBekp6L0IrN0dVd0NnWUlLb1pJemowRUF3SXcKY3pFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDa05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNURFZOaApiaUJHY21GdVkybHpZMjh4R1RBWEJnTlZCQW9URUc5eVp6R
      XVaWGhoYlhCc1pTNWpiMjB4SERBYUJnTlZCQU1UCkUyTmhMbTl5WnpFdVpYaGhiWEJzWlM1amIyMHdIaGNOTVRnd01qQTNNVFV4TmpBd1doY05NVGt3TWpBM01UVXgKTmpBd1dqQVFNUTR3REFZRFZRUURFd1ZoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQQpCSzltUVJZREp6K1JRV0FWS2Q2Z09wK0hZeXd4R1JpTDVYMVg3MGtCN3hMa
      TFQdVpaQ1kreUxRMzRJNHE1aWhxCm5nZklvZWZYSm1TWWRjT1hLSnBBcmlHamJEQnFNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEUKQWpBQU1CMEdBMVVkRGdRV0JCUjlqSmVRQnRwelk3WmlvZjRVdVlhclFhemtjekFyQmdOVkhTTUVKREFpZ0NCQwpPYW9OelhiYTdyaTZETnB3R0ZIUlJRVFRHcTBiTGQzYnJHcFhObDVKZkRBS0JnZ3Foa2pPUFFRREFnTklBREJGCkFpRUFwL09EbjFzdE15aWRYQXBDRy9PVE15a3dDQUQ2YUkwRThrRzRESXVhT1ZJQ0lIN00ybG5wNUZPZ2d4QmsKREFtTjRVZzNOclJ6YmR3MjNVRm9XYVVSQ29ibgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==.MEUCIQCKVWv0A8n9DafRUY9lygNV68tu/2oSbwIGVg4DoU6AkgIgYTpzaM692bwOj1x6h3cLObbgQInvvwl5L11IiI8l
      /1Y=
      {"id":"user1","type":"client","affiliation":"org1.department1","max_enrollments":1,"caName":""}
      2018/02/07 15:48:08 [DEBUG] Directing traffic to default CA
      2018/02/07 15:48:08 [DEBUG] Checking for revocation/expiration of certificate owned by 'admin'
      2018/02/07 15:48:08 [DEBUG] DB: Get certificate by serial (ee2476a62ee926d7da72981900cc9cff07eec65) and aki (4239aa0dcd76daeeb8ba0cda701851d14504d31aad1b2ddddbac6a57365e497c)
      2018/02/07 15:48:08 [DEBUG] Successful authentication of 'admin'
      2018/02/07 15:48:08 [DEBUG] Register request received
      2018/02/07 15:48:08 [DEBUG] Received registration request from admin: &{RegistrationRequest:{Name:user1 Type:client Secret:<<user-specified>> MaxEnrollments:1 Affiliation:org1.department1 Attributes:[] CAName:}}
      2018/02/07 15:48:08 [DEBUG] canRegister - Check to see if user admin can register
      2018/02/07 15:48:08 [DEBUG] DB: Getting identity admin
      2018/02/07 15:48:08 [DEBUG] Validate ID
      2018/02/07 15:48:08 [DEBUG] An affiliation is required for identity type client
      2018/02/07 15:48:08 [DEBUG] Validating affiliation: org1.department1
      2018/02/07 15:48:08 [DEBUG] DB: Get affiliation org1.department1
      2018/02/07 15:48:08 [DEBUG] Registering user id: user1
      2018/02/07 15:48:08 [DEBUG] Max enrollment value verification - User specified max enrollment: 1, CA max enrollment: -1
      2018/02/07 15:48:08 [DEBUG] DB: Getting identity user1
      2018/02/07 15:48:08 [DEBUG] DB: Add identity user1
      2018/02/07 15:48:08 [DEBUG] Successfully added identity user1 to the database
      2018/02/07 15:48:08 [DEBUG] Registration completed - sending response 0xc420026738
      2018/02/07 15:48:08 [INFO] 192.168.99.1:64526 - "POST /api/v1/register" 200

      2018/02/07 15:48:08 [DEBUG] Received request
      POST /api/v1/enroll
      Authorization: Basic dXNlcjE6QmV0TGlPRGNOY1Ft
      {"caName":"","certificate_request":"-----BEGIN CERTIFICATE REQUEST-----\r\nMIHMMHICAQAwEDEOMAwGA1UEAwwFdXNlcjEwWTATBgcqhkjOPQIBBggqhkjOPQMB\r\nBwNCAAQiDBDNgiSVfNdPRNOL7ZzJQyiTPo0U8b1gYT9Td4gvLS1f1bsJfgkphbNa\r\naitaRJEFOiBtJo+wu4PAzbb+A/apoAAwDAYIKoZIzj0EAwIFAANIADBFAiEA5SoB\r\nfHqFFF6QjQC6QVyuwYnO+YR8PMWKyDTGiUqNoTICIB9F768qhgdM3U8KChTpHX1o\r\nfzBhsPT62DquF6vauX85\r\n-----END CERTIFICATE REQUEST-----\r\n"}
      2018/02/07 15:48:08 [DEBUG] Directing traffic to default CA
      2018/02/07 15:48:08 [DEBUG] DB: Getting identity user1
      2018/02/07 15:48:08 [DEBUG] DB: Login user user1 with max enrollments of 1 and state of 0
      2018/02/07 15:48:08 [DEBUG] Max enrollment value (1) of identity is greater than allowed by CA, using CA max enrollment value of -1
      2018/02/07 15:48:08 [DEBUG] Successfully incremented state for identity user1 to 1
      2018/02/07 15:48:08 [DEBUG] DB: identity user1 successfully logged in
      2018/02/07 15:48:08 [DEBUG] Identity/Pass was correct
      2018/02/07 15:48:08 [DEBUG] Received request for endpoint enroll
      2018/02/07 15:48:08 [DEBUG] Enrollment request: {SignRequest:{Hosts:[] Request:-----BEGIN CERTIFICATE REQUEST-----
      MIHMMHICAQAwEDEOMAwGA1UEAwwFdXNlcjEwWTATBgcqhkjOPQIBBggqhkjOPQMB
      BwNCAAQiDBDNgiSVfNdPRNOL7ZzJQyiTPo0U8b1gYT9Td4gvLS1f1bsJfgkphbNa
      aitaRJEFOiBtJo+wu4PAzbb+A/apoAAwDAYIKoZIzj0EAwIFAANIADBFAiEA5SoB
      fHqFFF6QjQC6QVyuwYnO+YR8PMWKyDTGiUqNoTICIB9F768qhgdM3U8KChTpHX1o
      fzBhsPT62DquF6vauX85
      -----END CERTIFICATE REQUEST-----
       Subject:<nil> Profile: CRLOverride: Label: Serial:<nil> Extensions:[]} CAName:}
      2018/02/07 15:48:08 [DEBUG] csrAuthCheck: enrollment ID=user1, CommonName=user1, Subject=<nil>
      2018/02/07 15:48:08 [DEBUG] CSR authorization check passed
      2018/02/07 15:48:08 [DEBUG] Checking CSR fields to make sure that they do not exceed maximum character limits
      2018/02/07 15:48:08 [INFO] signed certificate with serial number 428179354584540920558483988599924847781662764958
      2018/02/07 15:48:08 [DEBUG] DB: Insert Certificate
      2018/02/07 15:48:08 [DEBUG] Saved serial number as hex 4b0039ef21d4be5cc4d747cdf59577b298cd2f9e
      2018/02/07 15:48:08 [DEBUG] saved certificate with serial number 428179354584540920558483988599924847781662764958
      2018/02/07 15:48:08 [INFO] 192.168.99.1:64529 - "POST /api/v1/enroll" 200

    Similar to the admin enrollment, this program invokes a CSR and outputs
    the keys and eCert into the hfc-key-store subdirectory. So now we have
    identity material for two separate users: admin & user1. Time to
    interact with the ledger.

* Queries are how you read data from the ledger. This data is stored
  as a series of key/value pairs, and you can query for the value of
  a single key, multiple keys, or if the ledger is written in a rich
  data storage format like JSON - perform complex searches against it.

  Lets run our query.js program to return a list of all the cars on
  the ledger. We will use our second identity - user1 - as the signing
  entity for this application. The following line in our program specifies
  user1 as the signer:
    fabric_client.getUserContext('user1', true);

  Recall that the user1 enrollment material has already been placed into
  our hfc-key-store subdirectory, so we simply need to tell our application
  to grab that identity. With the user object defined, we can now proceed
  with reading from the ledger. A function that will query all the cars,
  queryAllCars, is preloaded in the app, so we can simply run the program
  as is:
    node query.js

    Running this resulted in the following command line error:
      Store path:/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/hfc-key-store
      Successfully loaded user1 from persistence
      error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
          at new createStatusError (/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/node_modules/grpc/src/client.js:65:15)
          at /Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/node_modules/grpc/src/client.js:568:15
      Query has completed, checking results
      error from query =  { Error: 14 UNAVAILABLE: Connect Failed
          at new createStatusError (/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/node_modules/grpc/src/client.js:65:15)
          at /Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/node_modules/grpc/src/client.js:568:15
        code: 14,
        metadata: Metadata { _internal_repr: {} },
        details: 'Connect Failed' }

      I quickly found a place in that script refering to localhost
      instead of 192.168.99.100. After making the switch I got the
      following:
        Store path:/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/hfc-key-store
        Successfully loaded user1 from persistence
        Query has completed, checking results
        Response is  [{"Key":"CAR0", "Record":{"colour":"blue","make":"Toyota","model":"Prius","owner":"Tomoko"}},{"Key":"CAR1", "Record":{"colour":"red","make":"Ford","model":"Mustang","owner":"Brad"}},{"Key":"CAR2", "Record":{"colour":"green","make":"Hyundai","model":"Tucson","owner":"Jin Soo"}},{"Key":"CAR3", "Record":{"colour":"yellow","make":"Volkswagen","model":"Passat","owner":"Max"}},{"Key":"CAR4", "Record":{"colour":"black","make":"Tesla","model":"S","owner":"Adriana"}},{"Key":"CAR5", "Record":{"colour":"purple","make":"Peugeot","model":"205","owner":"Michel"}},{"Key":"CAR6", "Record":{"colour":"white","make":"Chery","model":"S22L","owner":"Aarav"}},{"Key":"CAR7", "Record":{"colour":"violet","make":"Fiat","model":"Punto","owner":"Pari"}},{"Key":"CAR8", "Record":{"colour":"indigo","make":"Tata","model":"Nano","owner":"Valeria"}},{"Key":"CAR9", "Record":{"colour":"brown","make":"Holden","model":"Barina","owner":"Shotaro"}}]

      Success! These are the 20 cars. The ledger is a key/value based
      and in our implementation the key is CARO through CAR9. This will
      become important in a second

* Lets take a closer look at this program "query.js"

  The initial section of the application defines certain variables such as
  channel name, cert store location and network endpoitns. In our sample
  app, these variables have been baked-in, but in a real app these variables
  would have to be specifid by the developer:
    var channel = fabric_client.newChannel('mychannel');
    var peer = fabric_client.newPeer('grpc://192.168.99.100:7051');
    channel.addPeer(peer);

    var member_user = null;
    var store_path = path.join(__dirname, 'hfc-key-store');
    console.log('Store path:'+store_path);
    var tx_id = null;

  The following chunk is where we construct our query:
    // queryCar chaincode function - requires 1 argument, ex: args: ['CAR4'],
    // queryAllCars chaincode function - requires no arguments , ex: args: [''],
    const request = {
      //targets : --- letting this default to the peers assigned to the channel
      chaincodeId: 'fabcar',
      fcn: 'queryAllCars',
      args: ['']
    };

  When the application ran, it invoked the fabcar chaincode on the peer, ran
  the "queryAllCars" function within it, and passed no arguments to it.

  To look at the available functions within our smart contract, navigate to
  the chaincode/fabcar/go subdirectory at the root of fabric-samples and open
  fabcar.go

  You'll see that we have the following functions available:
    - initLedger
    - queryCar,
    - queryAllCars,
    - createCar,
    - changeCarOwner

  Lets take a closer look at the queryAllCars function to see how it interacts with the ledger:
    func (s *SmartContract) queryAllCars(APIstub shim.ChaincodeStubInterface) sc.Response {
      startKey := "CAR0"
      endKey := "CAR999"

      resultsIterator, err := APIstub.GetStateByRange(startKey, endKey)

  This defines the range of queryAllCars. Every car between CAR0 and CAR999. will be
  returned by the query.

* Lets go back to the "query.js" program dn edit the request to query Car4 instead
  of all the cars. By doing the following:
      const request = {
        //targets : --- letting this default to the peers assigned to the channel
        chaincodeId: 'fabcar',
        fcn: 'queryCar',
        args: ['CAR4']
      };

  Now run "node query.js":
    Store path:/Users/gabeharms/Desktop/Practice/fabric-samples/fabcar/hfc-key-store
    Successfully loaded user1 from persistence
    Query has completed, checking results
    Response is  {"colour":"black","make":"Tesla","model":"S","owner":"Adriana"}

  This is the correct response! Using the queryCar function, we can query against any
  key (e.g CAR1) and get whatever make, model, color, and owner corresponding to
  that car.

  At this point you should be comfortable with the basic query functions in the smart
  contract and the handful of parameters in the query program. Time to update the
  ledger...